### PR TITLE
Fix deprecated libp2p peerstore

### PR DESCRIPTION
**Pull request by munna0908**
# Description

Refactored the code to replace following packages

- github.com/golang/protobuf  --->  google.golang.org/protobuf/proto
- github.com/multiformats/go-multiaddr-net ---> github.com/multiformats/go-multiaddr/net
- github.com/libp2p/go-libp2p-peerstore  ---> github.com/libp2p/go-libp2p-core/peerstore

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

No breaking changes 

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Comment by lazartravica** [comment]
@munna0908 Congratulations on your first pull request! 🍰  Please resolve the merge conflicts with the develop branch so that we can run the test suites to ensure that everything is operating normally.

Thanks!

**Comment by munna0908** [comment]
> @munna0908 Congratulations on your first pull request! 🍰 Please resolve the merge conflicts with the develop branch so that we can run the test suites to ensure that everything is operating normally.
> 
> Thanks!

@lazartravica merge conflicts resolved

**Review by Kourin1996 — APPROVED** [review]
Looks ok. It works locally without any issues. Thank you for the fixes 👏

**Review by zivkovicmilos — APPROVED** [review]
Confirming everything ran smoothly after these changes 👍 

Great work 💯 
[Test Results](https://github.com/0xPolygon/polygon-sdk/files/6998716/Test.Results.Run.all.tests.pdf)

**Review by lazartravica — APPROVED** [review]
Everything works as it should, good job 🤘

**Review by Vuksan — APPROVED** [review]
LGTM 🚀

**Pull request merged**
