### PR TITLE
Allow omitted `params` in json-rpc request

### PR DESCRIPTION
**Pull request by dankostiuk**
# Description

According to the official json-rpc spec [here](https://www.jsonrpc.org/specification#request_object), the `params` member "MAY be omitted". 

This bug was found after testing the integration with a blockchain bridge component that expected a non-error response when calling:
```
{"id":"1","jsonrpc":"2.0","method":"eth_chainId"}
```

The above request returns a successful response when testing on Polygon Mainnet.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by Kourin1996 — CHANGES_REQUESTED** [review]
Thank you for your improvement! Looks good to me and it works locally.

Probably we can also skip preparing argument array for unmarshalling in this case. I would be very grateful if you could put following codes into if block:
https://github.com/0xPolygon/polygon-sdk/blob/d7aa445e2da21c146790ece84050af7fa19f05af/jsonrpc/dispatcher.go#L300-L305

**Comment by Kourin1996** [comment]
@dankostiuk Thank you for modifying. After some tests, I noticed I could call an endpoint which needs arguments without params. (for example, you can call `eth_getBlockByNumber` without params) I think it should reject in this case.
@lazartravica @zivkovicmilos What do you think about this?

**Comment by lazartravica** [comment]
> @dankostiuk Thank you for modifying. After some tests, I noticed I could call an endpoint which needs arguments without params. (for example, you can call `eth_getBlockByNumber` without params) I think it should reject in this case.
> @lazartravica @zivkovicmilos What do you think about this?

@Kourin1996 I'd say to leave it as it is allowing for optional params. If omitting the params object doesn't cause errors in certain endpoints, but rather has undocumented functionality we can fix it later and approve this PR.

**Review by Kourin1996 — APPROVED** [review]
Looks good to me. Thank you for creating PR!

**Review by lazartravica — APPROVED** [review]

**Pull request merged**
