### PR TITLE
Code improvements on loadbot/refactor

### PR DESCRIPTION
**Pull request by Kourin1996**
# Description

This PR improves the code of loadbot being developed on `loadbot/refactor` branch

- Increment nonce first because there may have been nonce conflict among goroutines
- Fix handling private key prefix
- Use `WaitForReceipt` instead of `WaitUntilTxPoolEmpty` because TxPool wouldn't be empty in testnet because of existence of other transactions
- Check to verify the given jsonrpc URL

Here's is the link to docs [PR](https://github.com/0xPolygon/polygon-sdk-docs/pull/35)

This PR contains the change of `loadbot/refactor` created by @PtitLuca. The target branch of PR has been switched to `develop` so that we merge both change in one PR.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

**Review by brkomir — APPROVED** [review]
Looks good!

**Review by zivkovicmilos — APPROVED** [review]
Lookin' good 💯

**Comment by zivkovicmilos** [comment]
@munna0908 @Kourin1996 

It might not be a bad idea to update the `loadbot/refactor` branch first with the latest changes from develop before merging this PR

**Review by lazartravica — APPROVED** [review]
LGTM!

**Review by brkomir — APPROVED** [review]

**Review by zivkovicmilos — APPROVED** [review]
Thank you for simplifying the code 👍 

It's much more concise now, and more importantly - pending issues have been resolved.

Looks great 💯

**Pull request merged**
