### PR TITLE
Add output flag to polybft-secrets

### PR DESCRIPTION
**Pull request by vcastellm**
# Description

The output flag indicates the secrets command that it should output the existing secrets in case they are found in local disk or in the vault configured in the secrets manager conf.

Example usages:

`$ polygon-edge polybft-secrets --data-dir test-chain- --insecure --output --num 4`
`$ polygon-edge polybft-secrets --data-dir test-chain-1 --insecure --output `

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [x] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

CLI

# Documentation update

### CODE REVIEW

**Review by begmaroman — APPROVED** [review]

**Comment by Stefan-Ethernal** [comment]
Leaving a couple of comments:
- maybe we should consider putting `--account` and `--network` mutually exclusive to `--output`, because if we don't already have keys generated, command execution will fail.
- when having secrets already generated in local, I'm not able to output all the secrets at once. Namely this command is failing:
`go run . polybft-secrets --data-dir test-chain- --insecure --output`
with following error message
`failed to read account data: unable to read secret from disk (test-chain-/consensus/validator.key), open test-chain-/consensus/validator.key: no such file or directory`.

**Comment by vcastellm** [comment]
> * when having secrets already generated in local, I'm not able to output all the secrets at once. Namely this command is failing:
>   `go run . polybft-secrets --data-dir test-chain- --insecure --output`
>   with following error message
>   `failed to read account data: unable to read secret from disk (test-chain-/consensus/validator.key), open test-chain-/consensus/validator.key: no such file or directory`.

Take a look to the path, you need to specify the `--num` param if you are relying in our local "automagic" folders 😄

**Comment by vcastellm** [comment]
> * maybe we should consider putting `--account` and `--network` mutually exclusive to `--output`, because if we don't already have keys generated, command execution will fail.

It works if you specify the same command used to generate the secrets, eg:
`$polygon-edge polybft-secrets --data-dir test-chain- --insecure --num 4 --output --account=false`

🤔

**Comment by Stefan-Ethernal** [comment]
> It works if you specify the same command used to generate the secrets, eg: `$polygon-edge polybft-secrets --data-dir test-chain- --insecure --num 4 --output --account=false`

Ok seems like you are right, it is working properly when `--num` is submitted. 😉 
If secrets are generated already, we don't need to provide neither `--account` nor `--network` flags.

As a side note: it is anyways going to output public identities (ECDSA address, BLS public key and p2p node id) with or without `--output` provided when generating secrets. Not sure do we want to change it? 🤔 Probably doesn't matter... WDYT?

**Review by Stefan-Ethernal — APPROVED** [review]
LGTM

**Review by goran-ethernal — APPROVED** [review]

**Comment by vcastellm** [comment]
> As a side note: it is anyways going to output public identities (ECDSA address, BLS public key and p2p node id) with or without `--output` provided when generating secrets. Not sure do we want to change it? 🤔 Probably doesn't matter... WDYT?

It's convenient to have the output when generating the secrets, but we need also a way to print them, because for example, in cloud secrets, are not stored in FS

**Pull request merged**
