### PR TITLE
Update Staking SC bytecode for PR#14 in staking-contract

### PR DESCRIPTION
**Pull request by Kourin1996**
# Description

Please provide a detailed description of what was done in this PR

This PR updates Staking SC bytecode based on latest implementation in https://github.com/0xPolygon/staking-contracts/pull/14

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

1. Please setup PoS chain and specify `min-validator-count`, `max-validator-count` to the same number of initial validators and premine balance for an account.

```bash
go run ./main.go genesis --consensus ibft --ibft-validators-prefix-path test-chain- --pos --min-validator-count 4 --max-validator-count 4 \
--premine 0x... \
--bootnode /ip4/127.0.0.1/tcp/11001/p2p/... \
--bootnode /ip4/127.0.0.1/tcp/12001/p2p/... \
--bootnode /ip4/127.0.0.1/tcp/13001/p2p/... \
--bootnode /ip4/127.0.0.1/tcp/14001/p2p/... 
```

2. Start PoS chain
3. Stake less amount than the threshold for validator from the premined account. Please check this tx is successful.
4. Stake more amount than the threshold for validator from the premined account. Please check this tx fails.
5. Unstake from the premined account. Please check this tx is successful.

# Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

**Review by zivkovicmilos — CHANGES_REQUESTED** [review]
The bytecodes don't match for some reason when I compile and compare it with your bytecode.

Please make sure they match 🙏 
Capture

**Comment by 0xAleksaOpacic** [comment]
> The bytecodes don't match for some reason when I compile and compare it with your bytecode.
> 
> Please make sure they match 🙏 Capture

I have checked with deployedBytecode from (staking-contract/artifacts/contracts/staking.json after new build) and it does match. Also, I have tested it manually and it works. @zivkovicmilos can you please double-check this comment

**Review by 0xAleksaOpacic — APPROVED** [review]

**Comment by STZeed** [comment]
Sorry My bad

**Review by zivkovicmilos — APPROVED** [review]
For some reason the bytecode, when compiled on a Windows machine, doesn't match 🤷‍♂️ 

Lookin' good 💯

**Comment by STZeed** [comment]
GOOD 👍

**Pull request merged**
