### PR TITLE
EVM-440-Using-UTC-time

### PR DESCRIPTION
**Pull request by goran-ethernal**
# Description

Using local validators’ time zones may result in chain fork. So through this PR, we are using the `UTC` time throughout the code.

PR also introduces a lint rule that checks if `time.Now` variations are being used in code without calling the `UTC` function as well.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### CODE REVIEW

**Review by vcastellm — CHANGES_REQUESTED** [review]
I don't find it necessary to create a package out of the stdlib for wrapping the same calls to the stdlib, it creates unnecessary roundtrip for the reader, the value provided is very limited and it's very prone to be skipped in new code.

I vote for just using stdlib

**Comment by goran-ethernal** [comment]
@vcastellm Those were my initial thoughts as well, but I've gone with Evgeny's proposal on that task, to have it wrapped for easier usage. I am down whatever we find more comfortable.

**Review by vcastellm — APPROVED** [review]
LGTM

**Review by Stefan-Ethernal — APPROVED** [review]
🚀

**Review by igorcrevar — APPROVED** [review]

**Pull request merged**
