### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pucedoteth**
# Description

I have updated the document link which takes you directly to polygon edge. the replaced link took you to not found page.
# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [x] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [ ] I have tested this code manually

# Documentation update

I have updated the document link which takes you directly to polygon edge. the replaced link took you to not found page.

### CODE REVIEW

**Comment by Stefan-Ethernal** [comment]
Thanks for your PR. First of all, note that you need to sign the CLA. That is being done by providing this comment by yourself:
> I have read the CLA Document and I hereby sign the CLA

Also there are a couple of more places in the README files, that needs to change, because they point out to the obsolete URLs:
- `docker/README.md`:

| Old URL | New URL |
| :---:| :---: |
| https://wiki.polygon.technology/docs/supernets/operate/supernets-param-reference | https://wiki.polygon.technology/docs/edge/operate/param-reference/ |
| https://wiki.polygon.technology/docs/supernets | https://wiki.polygon.technology/docs/edge/ |

- `scripts/README.md`:

| Old URL | New URL |
| :---: | :---: |
| https://wiki.polygon.technology/docs/supernets/operate/supernets-param-reference | https://wiki.polygon.technology/docs/edge/operate/param-reference/ |
| https://wiki.polygon.technology/docs/supernets | https://wiki.polygon.technology/docs/edge/ |

**Review by Nemanja0x — APPROVED** [review]

**Comment by pucedoteth** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pucedoteth** [comment]
> Thanks for your PR. First of all, note that you need to sign the CLA. That is being done by providing this comment by yourself:
> 
> > I have read the CLA Document and I hereby sign the CLA
> 
> Also there are a couple of more places in the README files, that needs to change, because they point out to the obsolete URLs:
> 
> * `docker/README.md`:
> 
> Old URL	New URL
> https://wiki.polygon.technology/docs/supernets/operate/supernets-param-reference	https://wiki.polygon.technology/docs/edge/operate/param-reference/
> https://wiki.polygon.technology/docs/supernets	https://wiki.polygon.technology/docs/edge/
> * `scripts/README.md`:
> 
> Old URL	New URL
> https://wiki.polygon.technology/docs/supernets/operate/supernets-param-reference	https://wiki.polygon.technology/docs/edge/operate/param-reference/
> https://wiki.polygon.technology/docs/supernets	https://wiki.polygon.technology/docs/edge/

i have signed CLA and done your request in #1956 , #1955

**Comment by Stefan-Ethernal** [comment]
> done your request in https://github.com/0xPolygon/polygon-edge/pull/1956 , https://github.com/0xPolygon/polygon-edge/pull/1955

Sorry for bothering you, but can you incorporate changes from #1955 and #1956 to this PR as well, so that we can review it and merge together?

**Review by Stefan-Ethernal — APPROVED** [review]

**Comment by pucedoteth** [comment]
> > done your request in #1956 , #1955
> 
> Sorry for bothering you, but can you incorporate changes from #1955 and #1956 to this PR as well, so that we can review it and merge together?

all done ser

**Pull request merged**
