### PR TITLE
fix eth_getStorageAt always returning 0

### PR DESCRIPTION
**Pull request by typestring**
# Description

Please provide a detailed description of what was done in this PR

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests
I've tested this PR following this issue [#1447](https://github.com/0xPolygon/polygon-edge/issues/1447)

# Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it

# Additional comments

The RLP Parsing is already being done by the Snapshot's GetStorage method

https://github.com/0xPolygon/polygon-edge/blob/ed61412225766b716ce49babd30014a14db87b89/state/immutable-trie/snapshot.go#L41-L53

### CODE REVIEW

**Comment by typestring** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by typestring** [comment]
recheck

**Comment by typestring** [comment]
recheck

**Comment by Stefan-Ethernal** [comment]
@typestring Tnx for your PR.

A couple of notes:
- seems like there are unused imports in `eth_endpoint.go` and because of that, build, and consequently all the other CI checks, are failing at the moment (https://github.com/0xPolygon/polygon-edge/actions/runs/5016718450/jobs/8997304506). So remove all the unused imports.
- there is an e2e test (https://github.com/0xPolygon/polygon-edge/blob/develop/e2e-polybft/e2e/jsonrpc_test.go#L148-L163), which tests `eth_getStorageAt` endpoint, however it does not try to alter `TestSimple.sol` contract's state and then read it, but just testing a scenario where nothing is written into storage and retrieving default value (`0x0`). It would be awesome if you could add a scenario with sending a transaction, which would alter state of `TestSimple.sol` (you would probably need to change `TestSimple` SC and provide a setter) and then assert that given value is exactly the one you have set.
- rename mentioned test from `eth_getStorage` to `eth_getStorageAt`.

Does it make sense?

**Pull request closed without merging**
