### PR TITLE
Add unit tests for syncer

### PR DESCRIPTION
**Pull request by Kourin1996**
# Description

This PR adds unit tests for syncer in protocol package

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

**Review by zivkovicmilos — APPROVED** [review]
Lookin' good 💯

**Review by lazartravica — CHANGES_REQUESTED** [review]
👌 💪 

But before approving, just 2 questions out of curiousity:

1. `purgeBlocks` fix in protocol/syncer.go => how did the problem appear, what can the given error cause?
2. Why did you in some tests use the term `User` and in others `Peer`? Shouldn't they all be Peers?

**Comment by Kourin1996** [comment]
> purgeBlocks fix in protocol/syncer.go => how did the problem appear, what can the given error cause?

purgeBlocks removes a block with given hash and before that, because syncer expects next block from latest block. For that reason, I fixed. I think original code should work because syncer just try to write latest block to own chain again in the first time.

> Why did you in some tests use the term User and in others Peer? Shouldn't they all be Peers?

I just match test name with the target function.
Renamed at https://github.com/0xPolygon/polygon-sdk/pull/175/commits/0780729f98c3c1f0c843588b0973c1223aac3e8f

**Review by lazartravica — APPROVED** [review]
@Kourin1996 LGTM! Feel free to merge

**Pull request merged**
