### PR TITLE
Upgrade minimum go version to 1.16

### PR DESCRIPTION
**Pull request by 0xpanoramix**
Fixes EDGE-384

# Description

This PR updates the go modules using `go mod tidy -go=1.16`.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [X] I have tested this code with the official test suite
- [ ] I have tested this code manually

### CODE REVIEW

**Review by Kourin1996 — APPROVED** [review]
Looks good to me. 
@lazartravica @zivkovicmilos Do we need to run `go mod vendor` in this PR?

**Comment by Kourin1996** [comment]
@PtitLuca 
Can you check the version in .github/workflows/main.yml and .github/workflows/release.yml? Because they use 1.17.z partially

**Review by zivkovicmilos — CHANGES_REQUESTED** [review]
Thank you for opening up this PR 🙏 

There are a couple of additional steps you need to take, that were left out of this PR for some reason:
* You need to run `go mod vendor` to update the vendor directory, after touching the `go.mod` file
* You need to update the workflow and release YAML files to be up to date with go version `1.16` and not `1.17`, as per @Kourin1996's [comment](https://github.com/0xPolygon/polygon-edge/pull/413#issuecomment-1036455395) 
* You need to make sure the docs are updated to reflect the GO version, and any READMEs
* You need to make sure the Gitbook docs are up to date as well for the go version
* You need to resolve pending conflicts with the `develop` branch

**Review by zivkovicmilos — APPROVED** [review]
Thank you for clearing up the conflicts🙏 
Looks good 💯

**Review by 0xAleksaOpacic — APPROVED** [review]
Looks good

**Review by Kourin1996 — APPROVED** [review]
Looks good. Thank you for checking

**Pull request merged**
