### PR TITLE
Refactor parts of the trie package

### PR DESCRIPTION
**Pull request by zivkovicmilos**
# Description

This PR refactors some legacy parts of the trie package so they're more understandable, and adds coverage tests.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Comment by zivkovicmilos** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by zivkovicmilos** [comment]
recheck

**Comment by dbrajovic** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dbrajovic** [comment]
recheck

**Review by Kourin1996 — APPROVED** [review]
LGTM 👍

**Review by 0xAleksaOpacic — APPROVED** [review]
Well done!

**Review by lazartravica — APPROVED** [review]

**Pull request merged**
