### PR TITLE
Fix/existing txn

### LINKED ISSUE #267: txpool's `addImpl()` called twice for same tx resulting in many error logs
### Description

Since we've updated our testnet to include the changes introduced in https://github.com/0xPolygon/polygon-sdk/pull/256, we've observed many `nonce too low` errors appear in our logs as a result of all incoming tx's having a nonce 1 less than expected:
https://github.com/0xPolygon/polygon-sdk/blob/80896f6aacd0f2bc6fec4ba8bf637890dc7ad713/txpool/txpool.go#L384

After some debugging, we found that `addImpl()` is being called twice for the same tx hash. Although the first tx gets queued and promoted as expected, it seems that same tx goes through `addImpl()` again and is discarded.

To help get a better idea of how these txs are processed, I've added log outputs `nonceCheck 1` which compares the tx.Nonce with the nonce derived from `t.store.GetNonce()` within `validateTx()`:
https://github.com/0xPolygon/polygon-sdk/blob/80896f6aacd0f2bc6fec4ba8bf637890dc7ad713/txpool/txpool.go#L758

and `noneCheck 2` which compares the tx.Nonce with the nextNonce (derived from the `accountQueue.nextNonce`):
https://github.com/0xPolygon/polygon-sdk/blob/80896f6aacd0f2bc6fec4ba8bf637890dc7ad713/txpool/txpool.go#L377

Looking at the nonce values in the logs below, it appears that the nonce check within `validateTx` is outdated and the conditional check passes. Later on however we compare to the in-memory nonce and return the ErrNonceTooLow error.

We're not sure whether or not this is the intended/expected behaviour here - if this is indeed the expected flow, may I suggest that we simply return nil rather than logging an ERROR message?

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `04489b9`
* branch that causes this issue `develop

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

We shouldn't see any `nonce too` errors in our logs.

### Actual behaviour

We see many errors in our logs.

### Logs

```
2021-12-03T00:27:11.191Z [DEBUG] polygon.dispatcher: request: method=eth_sendRawTransaction id=122
2021-12-03T00:27:11.192Z [DEBUG] polygon.txpool: nonceCheck 1 - validateTx: incomingNonce=53284 nextNonce=53284
2021-12-03T00:27:11.192Z [DEBUG] polygon.txpool: nonceTest - lockAccountQueue called: nextNonce=53284
2021-12-03T00:27:11.192Z [DEBUG] polygon.txpool: noneCheck 2 - addImpl: incomingNonce=53284 nextNonce=53284
2021-12-03T00:27:11.192Z [DEBUG] polygon.txpool: add txn: ctx=addTxn hash=0xeb8d9c9e575187dd1e839b7207777cc2f77a4fa6f3699208d2dfe49cc8afe6d4 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-12-03T00:27:11.192Z [DEBUG] polygon.txpool: nonceTest - lockAccountQueue called: nextNonce=53284
2021-12-03T00:27:11.192Z [DEBUG] polygon.txpool.account: nonceTest - next nonce set: oldValue=53284 newValue=53285
2021-12-03T00:27:11.193Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":122,"result":"0xeb8d9c9e575187dd1e839b7207777cc2f77a4fa6f3699208d2dfe49cc8afe6d4"}
2021-12-03T00:27:11.195Z [DEBUG] polygon.jsonrpc: handle: request={"method":"eth_blockNumber","params":[],"id":49,"jsonrpc":"2.0"}
2021-12-03T00:27:11.197Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=49
2021-12-03T00:27:11.197Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":49,"result":"0x7ba89"}
2021-12-03T00:27:11.197Z [DEBUG] polygon.txpool: nonceCheck 1 - validateTx: incomingNonce=53284 nextNonce=53284
2021-12-03T00:27:11.198Z [DEBUG] polygon.txpool: nonceTest - lockAccountQueue called: nextNonce=53285
2021-12-03T00:27:11.199Z [DEBUG] polygon.txpool: noneCheck 2 - addImpl: incomingNonce=53284 nextNonce=53285
2021-12-03T00:27:11.199Z [DEBUG] polygon.txpool: Rejecting tx [0xeb8d9c9e575187dd1e839b7207777cc2f77a4fa6f3699208d2dfe49cc8afe6d4] from account heap due to low nonce
```

### Proposed solution

Either `addImpl()` shouldn't be called twice for the same tx, or we should avoid returning an error response if this path is expected (for example if the Tx.Nonce is exactly 1 less than nextNonce).

### PR DESCRIPTION
**Pull request by munna0908**
# Description

This PR Fixes issue #267 .

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by lazartravica — CHANGES_REQUESTED** [review]
@munna0908 please merge develop, and rerequest review 🙏

**Comment by munna0908** [comment]
> @munna0908 please merge develop, and rerequest review 🙏

@lazartravica Done

**Review by lazartravica — APPROVED** [review]

**Review by Kourin1996 — APPROVED** [review]
LGTM 👌

**Review by zivkovicmilos — APPROVED** [review]
Looks great 🚀

**Review by dbrajovic — APPROVED** [review]

**Review by brkomir — APPROVED** [review]

**Pull request merged**
