### PR TITLE
build: update `go` directive in `go.mod` to 1.17

### PR DESCRIPTION
**Pull request by Juneezee**
# Description

Go 1.16 will soon reach end-of-life when Go 1.18 gets released in February 2022. This PR updates the `go` directive in `go.mod` file by running `go mod tidy -go=1.17` to enable [module graph pruning](https://golang.org/ref/mod#graph-pruning) and [lazy module loading](https://golang.org/ref/mod#lazy-loading).

**Note 1:** This does not prevent users with earlier Go versions from successfully building packages from this module.

**Note 2:** The additional `require` directive is used to record indirect dependencies for Go 1.17 or higher, see https://go.dev/ref/mod#go-mod-file-go.

Related to: https://github.com/0xPolygon/polygon-sdk/pull/316#discussion_r777449679

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

**Review by vcastellm — APPROVED** [review]
LGTM

**Review by vcastellm — APPROVED** [review]

**Review by 0xAleksaOpacic — APPROVED** [review]
Looks great. Thank you for this PR!

**Review by zivkovicmilos — APPROVED** [review]
Hey @Juneezee,

Thank you for taking the time to contribute 🙏 

Bumping the go version is something we should've done a long time ago.

Please make sure you've pulled the latest changes from the develop branch 👍 

Looks good to me 💯

**Comment by Juneezee** [comment]
Rebased 👍

**Review by brkomir — APPROVED** [review]

**Comment by zivkovicmilos** [comment]
Hey @Juneezee,

Please make sure you follow the CLA instructions from [this message](https://github.com/0xPolygon/polygon-edge/pull/324#issuecomment-1022326549), and also pull the latest changes from the develop branch 🙏

**Comment by Juneezee** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by zivkovicmilos** [comment]
Hey @Juneezee,

Sorry for the pings 🙂 

We've merged out all of the dependency updates we wanted, you can pull the latest changes from the develop branch 🙏

**Comment by Juneezee** [comment]
@zivkovicmilos Done 😸

**Review by zivkovicmilos — APPROVED** [review]

**Comment by lazartravica** [comment]
Hello @Juneezee, thank you for your contribution.

We have a separate effort right now to upgrade to Go 1.16 first across the board of the build / test pipelines as well as in the artifacts and teh docs.

I am closing this PR, hope you understand.

**Pull request closed without merging**
