### PR TITLE
Fix eth_getCode for non-empty accounts without code

### PR DESCRIPTION
**Pull request by tkporter**
# Description

Ran into an issue where `eth_getCode` would give an error for addresses that are "non-empty" (meaning their nonce, balance, or storage hash is non-zero), but they don't have any code.

Example of the error I'd see for an account that had a balance but no code:
```
$ cast code 0xBBA5a06C75b62dd43E7ab94a6C13696b6010B546 --rpc-url $RPC_URL
Error:
(code: -32600, message: unable to fetch code, data: None)
```

This is my understanding of the bug:

When an `eth_getCode` RPC comes in, it runs [this bit of code](https://github.com/0xPolygon/polygon-edge/blob/develop/jsonrpc/eth_endpoint.go#L684-L702) in `jsonrpc/eth_endpoint.go`:
```go
func (e *Eth) GetCode(address types.Address, filter BlockNumberOrHash) (interface{}, error) {
	header, err := GetHeaderFromBlockNumberOrHash(filter, e.store)
	if err != nil {
		return nil, err
	}

	emptySlice := []byte{}
	code, err := e.store.GetCode(header.StateRoot, address)

	if errors.Is(err, ErrStateNotFound) {
		// If the account doesn't exist / is not initialized yet,
		// return the default value
		return "0x", nil
	} else if err != nil {
		return argBytesPtr(emptySlice), err
	}

	return argBytesPtr(code), nil
}
```

When an account is empty, meaning it has all zero/default values for the nonce, balance, account storage root (as the `EmptyRootHash`), and code hash, `ErrStateNotFound` is returned by `e.store.GetCode`. So this results in these accounts correctly returning the code of `0x`.

However in a case where there's an account that is not empty but has no code, the db is called to get the code for the given code hash. It seems that the db doesn't have an entry for the empty code hash, so it returns an error.

I decided to add a check before actually making a db read, where if the empty code hash is being requested, just an empty byte slice is returned. I'm very open to this change being more appropriately made somewhere else!

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

I'm unsure if the change to the `State`'s `GetCode` function is totally backward compatible

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

Just ran it locally and made eth_getCode RPCs to the node

### CODE REVIEW

**Comment by tkporter** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by vcastellm — COMMENTED** [review]
LGTM but can you add a test for this case?

**Comment by Stefan-Ethernal** [comment]
recheck

**Review by Stefan-Ethernal — APPROVED** [review]

**Comment by Stefan-Ethernal** [comment]
Continuation of this PR is done through #1474 (namely implementing necessary test(s)).

**Pull request merged**
