### PR TITLE
Implement metrics that tracks the base fee

### PR DESCRIPTION
**Pull request by jp-imx**
# Description

I couldn't find a metric in Prometheus to monitor gas price, so I added this one. If there's already something I can use I'm happy to adopt it and close this.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [ ] I have tested this code manually

### Manual tests

Please complete this section if you ran manual tests for this functionality, otherwise delete it

# Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

**Review by Stefan-Ethernal — COMMENTED** [review]
Looks good, however, since this part of code is IBFT consensus protocol related, which is basically obsoleted, don't forget to register gauge here as well, which is related to polybft:
https://github.com/jp-imx/polygon-edge/blob/jp/add-basefee-gauge/consensus/polybft/consensus_metrics.go#L37

**Review by goran-ethernal — CHANGES_REQUESTED** [review]
Hey @jp-imx . Thanks for the PR. You added this metric only for ibft.

To actually add it for `polybft`, please check out file `consensus/polybft/consensus_metrics.go`, function `updateBlockMetrics`. You can add the given metric there.

**Comment by jp-imx** [comment]
Thanks for pointing that out @Stefan-Ethernal and @goran-ethernal. I've now updated this

**Review by Stefan-Ethernal — APPROVED** [review]
LGTM


Cc @DannyS03 in order to update docs if necessary.

**Review by goran-ethernal — APPROVED** [review]

**Pull request merged**
