### PR TITLE
Allow bridge ACLs to be updated by admin without checking if sender has permission to send transactions

### PR DESCRIPTION
**Pull request by dusan-maksimovic**
# Description

Allow bridge access control lists (ACLs) admins to update the allow/block lists without checking first if they are allowed/blocked to send other transactions to the chain by looking at TX ACLs. This is now aligned with the way admins of contract deployment ACLs can update their respective lists.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [ ] I have tested this code manually

### CODE REVIEW

**Review by Stefan-Ethernal — APPROVED** [review]

**Review by vcastellm — APPROVED** [review]
LGTM

**Comment by Stefan-Ethernal** [comment]
Just a minor consideration, although it is not strictly related to this PR, since this part of the code is changed anyway...

Could we merge these nested ifs for tx allow and block lists in order to be consistent?
From this
```go
if t.txnAllowList != nil {
		if t.txnAllowList.Addr() == contract.CodeAddress {
```

to this
```go
if t.txnAllowList != nil && t.txnAllowList.Addr() == contract.CodeAddress {
```

**Review by goran-ethernal — APPROVED** [review]

**Comment by dusan-maksimovic** [comment]
@Stefan-Ethernal I made the suggested change through [this](https://github.com/0xPolygon/polygon-edge/pull/1625/commits/56c06a2e2e972c302c06b6e001f6fe5202ddbf8f) commit.

**Review by stana-miric — APPROVED** [review]

**Review by Stefan-Ethernal — APPROVED** [review]
I like it :+1:

**Pull request merged**
