### PR TITLE
Fix Subnet Genesis Finalize

### PR DESCRIPTION
**Pull request by paulgoleary**
# Description

* Pulls in upstream fix from `ethgo`: https://github.com/umbracle/ethgo/commit/7700cae3ef42ec444051c2d03362b2e4056b0a9a
Bug in `ethgo` causes problems with finalize and also elsewhere - the bridge I believe.
* Changes genesis finalize to allows it to be re-run when the first step has been already been done. This change is not strictly necessary but convenient if the first attempt to finalize fails for some reason.

Please provide a detailed description of what was done in this PR

# Changes include

- [X] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [ ] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [X] I have tested this code manually

### Manual tests

Please complete this section if you ran manual tests for this functionality, otherwise delete it

# Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

**Review by Stefan-Ethernal — APPROVED** [review]
LGTM.

Just curious, do you remember what was the error message they were getting when running supernet command after it was initialized?

**Review by igorcrevar — APPROVED** [review]

**Review by vcastellm — APPROVED** [review]
LGTM

**Comment by vcastellm** [comment]
Can you rebase @paulgoleary ?

**Comment by Stefan-Ethernal** [comment]
> Can you rebase @paulgoleary ?

@vcastellm @paulgoleary FYI, I've rebased. If CI is :green_circle:, we can merge it.

**Pull request merged**
