### PR TITLE
Fix minor punctuation mistakes

### PR DESCRIPTION
**Pull request by SebastianSupreme**
# Description

Fixed minor punctuation mistakes in the docker README.

### CODE REVIEW

**Review by Stefan-Ethernal — APPROVED** [review]

**Comment by SebastianSupreme** [comment]
@vcastellm @stana-miric @igorcrevar Could one of you please approve this as well?

**Review by vcastellm — APPROVED** [review]

**Comment by vcastellm** [comment]
@SebastianSupreme you should sign the CLA

**Comment by SebastianSupreme** [comment]
what's that?

**Comment by SebastianSupreme** [comment]
@vcastellm @Stefan-Ethernal Could you merge this now, please?

**Comment by Stefan-Ethernal** [comment]
> @vcastellm @Stefan-Ethernal Could you merge this now, please?

As Victor already explained, you should sign CLA. You should add this comment:

> I have read the CLA Document and I hereby sign the CLA

(https://github.com/0xPolygon/polygon-edge/pull/774#issuecomment-1265267693).

Do it and then we are good to merge I'd say.

**Comment by SebastianSupreme** [comment]
@Stefan-Ethernal what is a CLA?

**Comment by Stefan-Ethernal** [comment]
> @Stefan-Ethernal what is a CLA?

A contributor license agreement (https://yahoo.github.io/oss-guide/docs/resources/what-is-cla.html#:~:text=A%20Contributor%20License%20Agreement%20(CLA,to%20an%20open%20source%20project.). By default it is mandatory that each contributor signs it first time they contribute to this repository.

**Comment by SebastianSupreme** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
