### PR TITLE
Add Codecov to the workflow

### PR DESCRIPTION
**Pull request by ZeljkoBenovic**
# Description

This PR adds Codecov support

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [x] I have tested this code manually

Fixes EDGE-430

### CODE REVIEW

**Comment by zivkovicmilos** [comment]
@ZeljkoBenovic 

Are we going to add the `codecov.yml` file in this PR?

**Comment by ZeljkoBenovic** [comment]
> @ZeljkoBenovic
> 
> Are we going to add the `codecov.yml` file in this PR?

There won't be `codecov.yaml` file. Everything is in the main workflow, were our tests are.

**Comment by zivkovicmilos** [comment]
> > @ZeljkoBenovic
> > Are we going to add the `codecov.yml` file in this PR?
> 
> There won't be `codecov.yaml` file. Everything is in the main workflow, were our tests are.

We don't need the `codecov.yaml` for the workflow, it's for the reports that it generates on PRs that are opened

**Review by zivkovicmilos — APPROVED** [review]
Thank you for adding this feature 🙏 

Please look into if we should add the `codecov.yaml` file.

One small step for man, one giant leap for Polygon Edge

**Review by dbrajovic — APPROVED** [review]

**Review by Kourin1996 — APPROVED** [review]
LGTM

**Pull request merged**
