### PR TITLE
Add --json flag to output json

### PR DESCRIPTION
**Pull request by Kourin1996**
# Description

Doc PR: https://github.com/0xPolygon/polygon-sdk-docs/pull/36

This PR adds `--json` flag to support json output in following commands: 
- `monitor`
- `status`
- `version`
- `ibft candidates`
- `ibft propose`
- `ibft snapshot`
- `ibft status`
- `peers add`
- `peers list`
- `peers status`
- `txpool add`
- `txpool status`
- `loadbot`
- `secrets init`

Example:
```bash
$ go run main.go ibft snapshot --grpc-address 127.0.0.1:25000 --json
{"number":300000,"hash":"0x39a512b9d4d829d7bca2732150645245fe9c9c37d94ba8552cbe2dbca51fc264","votes":[],"validators":["0x372FD577a8cB5B2F944be0630fEc14a947eB4Db0","0x0C452Ad7Ee0e03882F710989e3D1ab1E0C7493dF","0x1d992D6EC0BC9E38D581ef42a1DB7f41177e322D","0x3650b09076292B7D8564EaE00c97A24175B54FB5"]}
```

This PR contains small refactor around command
+ Remove `Meta` because only some commands refer this struct
+ Add `Base` to be embedded in each command struct in order to provide common structure and function
+ Add `GRPCFlag` to handle `--grpc-address` and provides a function to establish connection

### `monitor` command

```bash
$ go run main.go monitor --grpc-address localhost:11000 --json
{"events":{"added":[{"type":"added","number":84,"hash":"0x51d70f3f2c76343abc909218c39c72b6c6dde8d2ad337f770057d389c7eb80a6"}],"removed":[]}}
{"events":{"added":[{"type":"added","number":85,"hash":"0xce2a63f72ecefbb752e7f353a9886e5f7ed73d237048f869cc5196d45d5f494e"}],"removed":[]}}
```

### `status` command

```bash
$ go run main.go status --grpc-address localhost:11000 --json
{"chain_id":100,"current_block_number":164,"current_block_hash":"0xffc4298827ff2591ac7ce54a1916bfead6d6d5c85be5b458772c8e4e1f0a74f8","libp2p_address":"/ip4/127.0.0.1/tcp/11001/p2p/16Uiu2HAm8NHWPF826Zpt8xov1B5SyDf6eEygCWqiumNdbAe3bKUt"}
```

### `version` command

```bash
$ go run main.go version --json             
{"version":"0.1.0"}
```

### `ibft candidates` command

```bash
$ go run main.go ibft candidates --grpc-address localhost:11000 --json
{"candidates":[{"address":"0x9aFc51c7867f369371F238674ee4459556c5D2b5","vote":"ADD"}]}
```

### `ibft propose` command

```bash
$ go run main.go ibft propose --addr 0x9aFc51c7867f369371F238674ee4459556c5D2b5 --vote auth --grpc-address localhost:11000 --json
{"message":"Successfully voted for the addition of address [0x9aFc51c7867f369371F238674ee4459556c5D2b5] to the validator set"}
```

### `ibft snapshot` command

```bash
$ go run main.go ibft snapshot --grpc-address localhost:11000 --json
{"number":390,"hash":"0x2855ddb00486ed06d8135a46fef6e772100a279b8b5ae6d393a6ddf719f7c36b","votes":[{"proposer":"0xC30D78F750fEaeB2b84cF8686a4d655768d81aD7","address":"0x9aFc51c7867f369371F238674ee4459556c5D2b5","vote":"ADD"}],"validators":["0xC30D78F750fEaeB2b84cF8686a4d655768d81aD7","0x8bC0C94c8eE7717C12D37Fea8A17F38Ab99073C2","0x7b8685777c553523B5F8c722a797735795a6d053","0xb8Fb07e04585142a9e9541527dA669c5bd84caE5"]}
```

### `ibft status` command

```bash
$ go run main.go ibft status --grpc-address localhost:11000 --json
{"validator_key":"0xC30D78F750fEaeB2b84cF8686a4d655768d81aD7"}
```

### `peers add` command

```bash
$ go run main.go peers add --addr /ip4/127.0.0.1/tcp/11001/p2p/16Uiu2HAmBFWNg9PaHuQXzqyx6ksrvjFabTWGd3bYdJq7BjwC876N --grpc-address localhost:11000 --json
{"num_requested":1,"num_added":1,"peers":["/ip4/127.0.0.1/tcp/11001/p2p/16Uiu2HAmBFWNg9PaHuQXzqyx6ksrvjFabTWGd3bYdJq7BjwC876N"],"errors":null}
```

### `peers list`

```bash
$ go run main.go peers list --grpc-address localhost:11000 --json
{"peers":["16Uiu2HAkuhNdcZATVA8Uwf3JUpFNyuUR5wKDBQDAqBRi2kawh36q","16Uiu2HAmQ3V3BF4y9fT5KrPWrx9obnj9em7QjPfuav3bFQbnahd4","16Uiu2HAmQfY3KdFVMiTbGghgCx7oK66uCsxKiRxGnvBnuDjQ7ooZ"]}
```

### `peers status`

```bash
$ go run main.go peers status --peer-id 16Uiu2HAkuhNdcZATVA8Uwf3JUpFNyuUR5wKDBQDAqBRi2kawh36q --grpc-address localhost:11000 --json
{"id":"16Uiu2HAkuhNdcZATVA8Uwf3JUpFNyuUR5wKDBQDAqBRi2kawh36q","protocols":["/ipfs/id/1.0.0","/ipfs/id/push/1.0.0","/floodsub/1.0.0","/p2p/id/delta/1.0.0","/ipfs/ping/1.0.0","/libp2p/circuit/relay/0.1.0","/id/0.1","/disc/0.1","/meshsub/1.1.0","/meshsub/1.0.0","/syncer/0.1"],"addresses":["/ip4/127.0.0.1/tcp/13001"]}
```

### `txpool add`

```bash
$ go run main.go txpool add --from 0xcFc818dc5E93b9b8b1B8D4D604eF92baE9cbE5b4 --to 0xdEF8940B16A9bF0b9c575C3d803a12E09E66D60B --value 100 --gasPrice 1 --gasLimit 50000 --nonce 1 --grpc-address localhost:11000 --json
{"from":"0xcFc818dc5E93b9b8b1B8D4D604eF92baE9cbE5b4","to":"0xdEF8940B16A9bF0b9c575C3d803a12E09E66D60B","value":"100","gas_price":"1","gas_limit":50000}
```

### `txpool status`

```bash
$ go run main.go txpool status --grpc-address localhost:11000 --json
{"txs":0}
```

### `secrets init`

```bash
$ go run ./main.go secrets init --data-dir test-chain-1 --json
{"address":"0x9c0C981F7FBA3C34263911c86c00C46496393cb7","node_id":"16Uiu2HAmFcAKxJytbYmkhRsQdeVnwTK8hRmE2HUmt82wWTqAejJE"}
```

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

**Comment by Mum2541** [comment]
feature/cli-json-output

**Review by zivkovicmilos — APPROVED** [review]
This is a really great addition to the SDK, not just because it adds a new feature, but because it simplifies and standardizes the way command outputs are handled 👍 

Great PR 💯 

The only suggestion I've had is to add a prettify flag for the JSON output `--pretty`, which would properly format the JSON instead of having it sit in 1 line.

Something like:
```go
		val, err := json.MarshalIndent(tx, "", "    ")
		if err != nil {
			return "", err
		}

		return string(val), nil
```

Not sure if there are any benefits to this, apart from it just looking nice - but then again if users want to look at the output, they could just not use JSON.

@lazartravica @ZeljkoBenovic what do you guys think?

**Comment by Kourin1996** [comment]
> The only suggestion I've had is to add a prettify flag for the JSON output `--pretty`, which would properly format the JSON instead of having it sit in 1 line.

The main target to use `--json` is the one who wants to execute commands from script or program, I guessed. That's why I minified JSON. But not so hard to add `--pretty`, then please let me know if we need `--pretty`
@zivkovicmilos @lazartravica @ZeljkoBenovic

**Review by brkomir — APPROVED** [review]
Great job!

**Review by lazartravica — CHANGES_REQUESTED** [review]
Excellent work! Please add the `--json` flag to the `secrets` commands as well, and link the docs PR 🙏

**Comment by lazartravica** [comment]
> > The only suggestion I've had is to add a prettify flag for the JSON output `--pretty`, which would properly format the JSON instead of having it sit in 1 line.
> 
> The main target to use `--json` is the one who wants to execute commands from script or program, I guessed. That's why I minified JSON. But not so hard to add `--pretty`, then please let me know if we need `--pretty` @zivkovicmilos @lazartravica @ZeljkoBenovic

No need to add a `--pretty` flag since the only reason we are adding the JSON output is to make it machine readable, as it already is pretty enough for human eyes :)

**Comment by lazartravica** [comment]
> Excellent work! Please add the `--json` flag to the `secrets` commands as well, and link the docs PR 🙏



> Excellent work! Please add the `--json` flag to the `secrets` commands as well, and link the docs PR 🙏

P.S. The `secrets` command that already outputs the libp2p Node ID and Validator account should be the only one to support the `--json` flag.

**Comment by Kourin1996** [comment]
@lazartravica I've added `--json` flag into `secrets init` command. I've not added it for `secrets generate` and `genesis` although they produce json file originally. If you want to choose an option to show json instead of saving, let me know.

**Review by zivkovicmilos — APPROVED** [review]
Thank you for adding the requested changes 🙏 

Looks good to me 💯

**Review by lazartravica — APPROVED** [review]
LGTM! Feel free to merge the PRs

**Pull request merged**
